title: Redwood Lane
description: Expert Salesforce consulting, specializing in automation, integration, and custom development.
url: "https://redwoodlane.net"
baseurl: "" # Only set this if your site is hosted in a subfolder (leave it blank for GitHub Pages root)
author: Steven Van Elk
email: info@redwoodlane.net

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

# Permalinks and pagination
permalink: /blog/:title/
pagination:
  enabled: true
  per_page: 5
  permalink: /blog/page/:num/
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
  collection: posts

# Defaults to help SEO and layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Steven Van Elk
      description: "Insights, tips, and stories from a Salesforce consultant."
      tags: [Salesforce, Salesforce Administrator, Salesforce Developer, Salesforce Consulting, Consulting, CRM]

# Exclude non-web assets
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
